#!/usr/bin/env ruby
#^syntax detection

site 'https://supermarket.getchef.com/api/v1'

cookbook 'nginx'
cookbook 'hhvm'
cookbook 'services'
cookbook 'virtualbox-guest-additions'

cookbook "nginx-php-app",
  :git => "https://github.com/ktunkiewicz/nginx-php-app"

