#!/usr/bin/env ruby
#^syntax detection

site 'https://supermarket.getchef.com/api/v1'

cookbook 'hhvm'
cookbook 'services'
cookbook 'nginx'
cookbook 'php-fpm'

cookbook 'nginx-website',
  :git => "https://github.com/ktunkiewicz/nginx-website"

