#!/usr/bin/env ruby
#^syntax detection

site 'https://supermarket.getchef.com/api/v1'

cookbook 'hhvm'
cookbook 'services'
cookbook 'nginx'

cookbook 'nginx_website',
  :git => "https://github.com/ktunkiewicz/nginx_website"
